displayName: Traefik Aggregator
type: provider

iconPath: ./img/icon.png
bannerPath: ./img/icon.png

import: github.com/MadddinTribleD/traefikaggregator

summary: 'Traefik Aggregator Plugin'

testData:
  pollInterval: 2s
  instances:
    - apiEndpoint: http://<traefikInstance_1>:8080/api
      service:
        name: traefikInstance-1-web
        loadBalancer:
          servers:
            - url: http://<traefikInstance_1>:80
      allowedEndpoints:
        - web
      router:
        entryPoints:
          - web
        middlewares:
          - redirect-to-https@file
    - apiEndpoint: http://<traefikInstance_1>:8080/api
      service:
        name: traefikInstance-1-web-secured
        loadBalancer:
          servers:
            - url: https://<traefikInstance_1>:443
      allowedEndpoints:
        - web-secured
      router:
        entryPoints:
          - web-secured
        tls:
          enabled: true
      certResolverMapping:
        <remoteTlsResolve1>: <localTlsResolve1>
        <remoteTlsResolve2>: <localTlsResolve2>